# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 23a98eb58a55eaafc0a931972b88542c2a08675210199c91d1c4faaaec7b9cecf62f013bfb6d7a9fff4ff658ec8315cb4331e1a3610d72cf03dbfcfafa867c99

test:
  secret_key_base: bb07e211ba5f8bb3d670673e0abaea3a6a199ccb6201b6eb09f2d7f7427d0ff3ff2f65f8a4452a4317702b8ad906054372ddd9e051767c52eb5a2f23a79aa254
# =======
#   secret_key_base: edbac4ca3d7cdb1514c8a109829293627c5cfec9ee125c02aa6d96f385ec8f9020cd5afe4dc08e485e9eff19197b3ba967613a78e1a208b27f82f0891d1f6bf7
#
# test:
#   secret_key_base: 9ada0881c8096206cd4b3195237fe69f6ffcb9c7574b6d5769070317b10cf1b0603f09392ea5fc6fbe59028245f47294efe768b48c29d3ba9d0a03f4cd0c6056
# >>>>>>> initial commit

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
